// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WPF.HotelBooking.DataAccess;

namespace WPF.HotelBooking.DataAccess.Migrations
{
    [DbContext(typeof(HotelBookingDbContext))]
    partial class HotelBookingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WPF.HotelBooking.Model.Hotel", b =>
                {
                    b.Property<int>("HotelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("HotelId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            HotelId = 1,
                            Name = "Dreamland Circus Hotel",
                            Rating = 0
                        },
                        new
                        {
                            HotelId = 2,
                            Name = "Depressing Shack",
                            Rating = 0
                        },
                        new
                        {
                            HotelId = 3,
                            Name = "The House",
                            Rating = 0
                        },
                        new
                        {
                            HotelId = 4,
                            Name = "Dreamland Shack",
                            Rating = 0
                        },
                        new
                        {
                            HotelId = 5,
                            Name = "Depressing House",
                            Rating = 0
                        },
                        new
                        {
                            HotelId = 6,
                            Name = "Majestic House",
                            Rating = 0
                        },
                        new
                        {
                            HotelId = 7,
                            Name = "Dreamland Coffee Hotel",
                            Rating = 0
                        },
                        new
                        {
                            HotelId = 8,
                            Name = "Royal Coffee Hotel",
                            Rating = 0
                        },
                        new
                        {
                            HotelId = 9,
                            Name = "Royal Circus Hotel",
                            Rating = 0
                        });
                });

            modelBuilder.Entity("WPF.HotelBooking.UI.Model.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Allinclusive")
                        .HasColumnType("bit");

                    b.Property<bool>("Breakfast")
                        .HasColumnType("bit");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.Property<bool>("Transport")
                        .HasColumnType("bit");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("Booking");
                });

            modelBuilder.Entity("WPF.HotelBooking.UI.Model.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("RoomId");

                    b.HasIndex("HotelId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            RoomId = 1,
                            HotelId = 8,
                            Name = "Room 1",
                            Price = 0,
                            Size = 0
                        },
                        new
                        {
                            RoomId = 2,
                            HotelId = 8,
                            Name = "Room 2",
                            Price = 0,
                            Size = 0
                        },
                        new
                        {
                            RoomId = 3,
                            HotelId = 3,
                            Name = "Room 3",
                            Price = 0,
                            Size = 0
                        },
                        new
                        {
                            RoomId = 4,
                            HotelId = 5,
                            Name = "Room 4",
                            Price = 0,
                            Size = 0
                        },
                        new
                        {
                            RoomId = 5,
                            HotelId = 8,
                            Name = "Room 5",
                            Price = 0,
                            Size = 0
                        },
                        new
                        {
                            RoomId = 6,
                            HotelId = 7,
                            Name = "Room 6",
                            Price = 0,
                            Size = 0
                        },
                        new
                        {
                            RoomId = 7,
                            HotelId = 4,
                            Name = "Room 7",
                            Price = 0,
                            Size = 0
                        },
                        new
                        {
                            RoomId = 8,
                            HotelId = 7,
                            Name = "Room 8",
                            Price = 0,
                            Size = 0
                        },
                        new
                        {
                            RoomId = 9,
                            HotelId = 3,
                            Name = "Room 9",
                            Price = 0,
                            Size = 0
                        },
                        new
                        {
                            RoomId = 10,
                            HotelId = 6,
                            Name = "Room 10",
                            Price = 0,
                            Size = 0
                        },
                        new
                        {
                            RoomId = 11,
                            HotelId = 6,
                            Name = "Room 11",
                            Price = 0,
                            Size = 0
                        },
                        new
                        {
                            RoomId = 12,
                            HotelId = 6,
                            Name = "Room 12",
                            Price = 0,
                            Size = 0
                        },
                        new
                        {
                            RoomId = 13,
                            HotelId = 1,
                            Name = "Room 13",
                            Price = 0,
                            Size = 0
                        },
                        new
                        {
                            RoomId = 14,
                            HotelId = 3,
                            Name = "Room 14",
                            Price = 0,
                            Size = 0
                        },
                        new
                        {
                            RoomId = 15,
                            HotelId = 4,
                            Name = "Room 15",
                            Price = 0,
                            Size = 0
                        },
                        new
                        {
                            RoomId = 16,
                            HotelId = 4,
                            Name = "Room 16",
                            Price = 0,
                            Size = 0
                        },
                        new
                        {
                            RoomId = 17,
                            HotelId = 6,
                            Name = "Room 17",
                            Price = 0,
                            Size = 0
                        },
                        new
                        {
                            RoomId = 18,
                            HotelId = 5,
                            Name = "Room 18",
                            Price = 0,
                            Size = 0
                        },
                        new
                        {
                            RoomId = 19,
                            HotelId = 2,
                            Name = "Room 19",
                            Price = 0,
                            Size = 0
                        },
                        new
                        {
                            RoomId = 20,
                            HotelId = 4,
                            Name = "Room 20",
                            Price = 0,
                            Size = 0
                        },
                        new
                        {
                            RoomId = 21,
                            HotelId = 6,
                            Name = "Room 21",
                            Price = 0,
                            Size = 0
                        },
                        new
                        {
                            RoomId = 22,
                            HotelId = 6,
                            Name = "Room 22",
                            Price = 0,
                            Size = 0
                        },
                        new
                        {
                            RoomId = 23,
                            HotelId = 5,
                            Name = "Room 23",
                            Price = 0,
                            Size = 0
                        },
                        new
                        {
                            RoomId = 24,
                            HotelId = 8,
                            Name = "Room 24",
                            Price = 0,
                            Size = 0
                        },
                        new
                        {
                            RoomId = 25,
                            HotelId = 3,
                            Name = "Room 25",
                            Price = 0,
                            Size = 0
                        },
                        new
                        {
                            RoomId = 26,
                            HotelId = 8,
                            Name = "Room 26",
                            Price = 0,
                            Size = 0
                        },
                        new
                        {
                            RoomId = 27,
                            HotelId = 5,
                            Name = "Room 27",
                            Price = 0,
                            Size = 0
                        },
                        new
                        {
                            RoomId = 28,
                            HotelId = 7,
                            Name = "Room 28",
                            Price = 0,
                            Size = 0
                        },
                        new
                        {
                            RoomId = 29,
                            HotelId = 6,
                            Name = "Room 29",
                            Price = 0,
                            Size = 0
                        },
                        new
                        {
                            RoomId = 30,
                            HotelId = 2,
                            Name = "Room 30",
                            Price = 0,
                            Size = 0
                        },
                        new
                        {
                            RoomId = 31,
                            HotelId = 1,
                            Name = "Room 31",
                            Price = 0,
                            Size = 0
                        },
                        new
                        {
                            RoomId = 32,
                            HotelId = 4,
                            Name = "Room 32",
                            Price = 0,
                            Size = 0
                        },
                        new
                        {
                            RoomId = 33,
                            HotelId = 8,
                            Name = "Room 33",
                            Price = 0,
                            Size = 0
                        },
                        new
                        {
                            RoomId = 34,
                            HotelId = 1,
                            Name = "Room 34",
                            Price = 0,
                            Size = 0
                        },
                        new
                        {
                            RoomId = 35,
                            HotelId = 4,
                            Name = "Room 35",
                            Price = 0,
                            Size = 0
                        },
                        new
                        {
                            RoomId = 36,
                            HotelId = 2,
                            Name = "Room 36",
                            Price = 0,
                            Size = 0
                        },
                        new
                        {
                            RoomId = 37,
                            HotelId = 1,
                            Name = "Room 37",
                            Price = 0,
                            Size = 0
                        },
                        new
                        {
                            RoomId = 38,
                            HotelId = 5,
                            Name = "Room 38",
                            Price = 0,
                            Size = 0
                        },
                        new
                        {
                            RoomId = 39,
                            HotelId = 6,
                            Name = "Room 39",
                            Price = 0,
                            Size = 0
                        },
                        new
                        {
                            RoomId = 40,
                            HotelId = 4,
                            Name = "Room 40",
                            Price = 0,
                            Size = 0
                        },
                        new
                        {
                            RoomId = 41,
                            HotelId = 3,
                            Name = "Room 41",
                            Price = 0,
                            Size = 0
                        },
                        new
                        {
                            RoomId = 42,
                            HotelId = 1,
                            Name = "Room 42",
                            Price = 0,
                            Size = 0
                        },
                        new
                        {
                            RoomId = 43,
                            HotelId = 1,
                            Name = "Room 43",
                            Price = 0,
                            Size = 0
                        },
                        new
                        {
                            RoomId = 44,
                            HotelId = 3,
                            Name = "Room 44",
                            Price = 0,
                            Size = 0
                        },
                        new
                        {
                            RoomId = 45,
                            HotelId = 7,
                            Name = "Room 45",
                            Price = 0,
                            Size = 0
                        },
                        new
                        {
                            RoomId = 46,
                            HotelId = 7,
                            Name = "Room 46",
                            Price = 0,
                            Size = 0
                        },
                        new
                        {
                            RoomId = 47,
                            HotelId = 1,
                            Name = "Room 47",
                            Price = 0,
                            Size = 0
                        },
                        new
                        {
                            RoomId = 48,
                            HotelId = 6,
                            Name = "Room 48",
                            Price = 0,
                            Size = 0
                        },
                        new
                        {
                            RoomId = 49,
                            HotelId = 4,
                            Name = "Room 49",
                            Price = 0,
                            Size = 0
                        });
                });

            modelBuilder.Entity("WPF.HotelBooking.UI.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "new@gmail.com",
                            FirstName = "Test",
                            LastName = "Hej",
                            PhoneNumber = 0
                        });
                });

            modelBuilder.Entity("WPF.HotelBooking.UI.Model.Booking", b =>
                {
                    b.HasOne("WPF.HotelBooking.UI.Model.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId");

                    b.HasOne("WPF.HotelBooking.UI.Model.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId");

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WPF.HotelBooking.UI.Model.Room", b =>
                {
                    b.HasOne("WPF.HotelBooking.Model.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("WPF.HotelBooking.Model.Hotel", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("WPF.HotelBooking.UI.Model.User", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
